config/routes.rb
Rivers::Application.routes.draw do

  resources :rivers do
    member do
      get 'fetch'
    end
  end

  root 'rivers#index'
end

app/models/pearl.rb
class Pearl < ActiveRecord::Base

  belongs_to :river

  default_scope { order('published_at desc') }

end

app/models/river.rb
class River < ActiveRecord::Base

  has_many :pearls
  serialize :channel_ids, Array

  def self.generate_url(api_key, channel_id)
    "http://www.mynewsdesk.com/partner/api/1_0/#{api_key}/channel/#{channel_id}/material/list"
  end

  # add pearl from item to river
  # if item already saved, fetch and return pearl directly
  def add_pearl_from_item(item)
    params = item.clone
    params[:item_id] = item[:id]
    params.delete :id
    pearls.where(item_id: item[:id], type_of_media: item[:type_of_media]).first_or_create(params)
  end

  def urls
    channel_ids.map { |i| url_from_channel_id i }
  end

  private
  def url_from_channel_id(channel_id)
    River.generate_url api_key, channel_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rivers_controller.rb
class RiversController < ApplicationController
  def index
    @rivers = River.all
  end

  def show
    @river = River.find params[:id]
  end

  # fetch recently added pearls after the last_pearl_id
  # and return rendered pearls html as json
  def fetch
    river = River.find_by id: params[:id]
    error = nil
    if river.nil?
      error = 'river does not exist'
    else
      last_pearl = Pearl.find_by id: params[:last_pearl_id]
      if last_pearl.nil?
        error = 'last_pearl_id does not exist'
      else
        @pearls = river.pearls.where('published_at >= ? and id > ?', last_pearl.published_at, last_pearl.id)
      end
    end

    json_result = {}
    if error.nil?
      json_result[:pearls] = @pearls.map do |p|
        { html: render_to_string(partial: 'pearl', locals: { pearl: p } ) }
      end
    else
      json_result[:error] = error
    end
    
    render json: json_result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rivers_helper.rb
module RiversHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rivers</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/rivers/_pearl.html.erb
<li class="pearl" data-id="<%= pearl.id %>">
  <div class="web-image">
    <a href="<%= pearl.url %>" target="_blank">
      <img class="center" src="<%= pearl.image %>" alt="image" width="200">
    </a>
  </div>
  <div class="text">
    <h3 class="">
      <a href="<%= pearl.url %>" target="_bank"><%= pearl.header %></a>
    </h3>
    <p class="date text-center">
      <%= "#{pearl.published_at}" %>
    </p>
    <p class="description">
      <%= pearl.summary %>
    </p>
  </div>
  <%= pearl.header %>
</li>

app/views/rivers/index.html.erb
<div id="rivers-list">
  <h1>Rivers List</h1>
  <ul>
    <% @rivers.each do |river| %>
    <li><a href="<%= river_path(river) %>"><%= river.name %></a></li>
    <% end %>
  </ul>
</div>

app/views/rivers/show.html.erb
<div class="river-pearls">
  <div>
    <button class="js-add">Test Prepend</button>
  </div>
  <div class="loading">
    loading...
  </div>
  <ul id="pearls" data-id="<%= @river.id %>">
    <% @river.pearls.each do |p| %>
    <%= render partial: 'pearl', locals: { pearl: p } %>
    <% end %>
  </ul>
</div>